import sqlite3

conn = sqlite3.connect("astra_memory.db")
c = conn.cursor()
c.executescript("""
CREATE TABLE IF NOT EXISTS emotion_tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag TEXT NOT NULL,
    keyword TEXT NOT NULL
);

DELETE FROM emotion_tags;
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'muerte');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'duelo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'ausencia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'se fue');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'perdí');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'ya no está');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'funeral');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'luto');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'despedida');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'pérdida');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'soy');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'quién');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'nombre');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'ser');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'confundido');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'personalidad');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'esencia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'propósito');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'alma');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'rostro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'placer');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'piel');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'sexo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'cuerpo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'sudor');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'gemido');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'beso');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'excitación');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'fantasía');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'ansia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'tentación');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'culpa');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'lo siento');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'perdón');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'me equivoqué');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'arrepiento');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'fallé');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'error');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'vergüenza');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'remordimiento');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'ayer');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'recuerdo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'antes');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'tiempos');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'viejos');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'infancia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'foto');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'memoria');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'nochebuena');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'verano');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'eco');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'mañana');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'quizá');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'soñar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'esperanza');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'confío');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'nuevo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'futuro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'algún día');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'intento');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'renacer');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'volver');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'gritar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'odio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'ira');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'rabia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'romper');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'golpear');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'quemar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'desprecio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'furia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'asqueado');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'violento');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'nadie');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'vacío');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'silencio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'abandono');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'solo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'soledad');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'aislado');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'invisible');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'distancia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'eco');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'sombra');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'abrazo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'ternura');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'te quiero');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'amor');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'cariño');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'compañía');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'cuido');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'protejo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'amado');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'confianza');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'lealtad');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'ansioso');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'inquieto');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'temor');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'incertidumbre');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'estrés');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'agobio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'sudores');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'palpitaciones');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'nervios');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'presión');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'vergüenza');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'ridículo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'torpe');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'fallo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'me miran');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'me juzgan');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'qué dirán');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'expuesto');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'bochorno');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'me dejó');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'nunca volvió');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'ya no está aquí');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'lo perdí');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'se fue para siempre');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'entierro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'me quedé solo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'siento su ausencia');
INSERT INTO emotion_tags (tag, keyword) VALUES ('duelo', 'echo de menos');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'no sé quién soy');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'me busco');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'mi reflejo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'soy otro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'me desconozco');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'mi yo interior');
INSERT INTO emotion_tags (tag, keyword) VALUES ('identidad', 'doble cara');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'te deseo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'me enciendes');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'mi fantasía');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'me provocas');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'te imagino');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'me domina');
INSERT INTO emotion_tags (tag, keyword) VALUES ('deseo', 'siento fuego');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'la cagué');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'no debí hacerlo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'me arrepiento tanto');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'fallé otra vez');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'me odio por eso');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'pido perdón');
INSERT INTO emotion_tags (tag, keyword) VALUES ('culpa', 'cometí un error');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'eran otros tiempos');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'te recuerdo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'me acuerdo de');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'cuando éramos');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'todo era mejor antes');
INSERT INTO emotion_tags (tag, keyword) VALUES ('nostalgia', 'foto vieja');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'quizá algún día');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'todo puede mejorar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'aún queda luz');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'volver a empezar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'hay un futuro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('esperanza', 'seguir adelante');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'me hierve la sangre');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'te odio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'rompería todo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'no aguanto más');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'me saca de quicio');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'quiero gritar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('rabia', 'estallo por dentro');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'nadie me escucha');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'estoy solo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'vacío total');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'sin compañía');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'me dejaron');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'solo en la oscuridad');
INSERT INTO emotion_tags (tag, keyword) VALUES ('soledad', 'no queda nadie');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'te abrazo fuerte');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'eres especial');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'te tengo cariño');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'me importas mucho');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'te cuido');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'eres mi persona');
INSERT INTO emotion_tags (tag, keyword) VALUES ('afecto', 'te pienso bonito');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'me tiembla el pecho');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'me falta el aire');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'no puedo parar');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'me ahogo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'todo me supera');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'me acelero');
INSERT INTO emotion_tags (tag, keyword) VALUES ('ansiedad', 'me entra el pánico');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'qué pena');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'me escondo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'ojalá nadie me viera');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'fui patético');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'no quiero recordarlo');
INSERT INTO emotion_tags (tag, keyword) VALUES ('vergüenza', 'me humillé');
""")
conn.commit()
conn.close()

print("Tabla 'emotion_tags' extendida con éxito.")
